In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
MATRIX = torch.tensor([[1, 4, 5], [3, 4, 6]])
MATRIX

tensor([[1, 4, 5],
        [3, 4, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([[[1, 3, 2, 1], [2, 4, 6, 7], [2, 3, 5, 6], [3, 4, 5, 6]]])
TENSOR

tensor([[[1, 3, 2, 1],
         [2, 4, 6, 7],
         [2, 3, 5, 6],
         [3, 4, 5, 6]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 4])

In [ ]:
TENSOR[0][0]

tensor([1, 3, 2, 1])

In [ ]:
rand_tensor = torch.rand(size=(3, 4))
rand_tensor

tensor([[0.8796, 0.9087, 0.3683, 0.6154],
        [0.6865, 0.1355, 0.5970, 0.3208],
        [0.4681, 0.3659, 0.7660, 0.3311]])

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
rand_tensor.dtype

torch.float32

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Using arange and tensor_like in Pytorch

In [ ]:
# Using arange function
zero_to_nine = torch.arange(0, 10)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1, end= 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating zeroes like tensor
zeroes_like = torch.zeros_like(input = one_to_ten)
zeroes_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Data Types 16bit 32 bit float

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [ ]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 3., 12., 27.])

In [ ]:
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

**Tensor Information**

In [ ]:
float_64_tensor = torch.tensor([3.0, 4.5, 7.8, 9.0], dtype=torch.float64)
print(float_64_tensor)

tensor([3.0000, 4.5000, 7.8000, 9.0000], dtype=torch.float64)


In [ ]:
float_16_tensor = float_64_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
random_tensor = torch.rand(size=(4, 5))
print(random_tensor)
print(f"Data type: {random_tensor.dtype}")
print(f"Size or Shape: {random_tensor.shape}")
print(f"Size or Shape: {random_tensor.size()}")
print(f"Device: {random_tensor.device}")


tensor([[0.4754, 0.7662, 0.8985, 0.5804, 0.3151],
        [0.3452, 0.6396, 0.0537, 0.0340, 0.2209],
        [0.4418, 0.9243, 0.9109, 0.3854, 0.2321],
        [0.5305, 0.6342, 0.9444, 0.2983, 0.9621]])
Data type: torch.float32
Size or Shape: torch.Size([4, 5])
Size or Shape: torch.Size([4, 5])
Device: cpu


MATRIX MANIPULATION:
* ADDITION
* SUBTRACTION
* MUL ELEMENT WISE
*DIVISION
*MATRIX MUL

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
tensor - 12

tensor([-2,  8, 18])

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
tensor = tensor / 2
tensor

tensor([ 5., 10., 15.])

In [ ]:
torch.add(tensor, 12)

tensor([17., 22., 27.])

In [ ]:
tensor

tensor([ 5., 10., 15.])

In [ ]:
tensor = torch.mul(tensor, 2)
tensor

tensor([10., 20., 30.])

MATRIX MULTIPLICATION (DOT PRODUCT)

In [ ]:
tensor

tensor([10., 20., 30.])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
print(tensor ,"*", tensor)
print(f"Equals:  {tensor * tensor}")

tensor([10., 20., 30.]) * tensor([10., 20., 30.])
Equals:  tensor([100., 400., 900.])


In [ ]:
# Vector Multiplication of Tensor with itself
%%time
print(torch.matmul(tensor, tensor))

tensor(1400.)
CPU times: user 2.07 ms, sys: 12 µs, total: 2.09 ms
Wall time: 6.84 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 43 µs, sys: 7 µs, total: 50 µs
Wall time: 53.4 µs


tensor(1400.)

In [ ]:
%%time
sum = 0
for i in range(len(tensor)):
  sum += tensor[i] * tensor[i]
print(sum)

tensor(1400.)
CPU times: user 1.83 ms, sys: 0 ns, total: 1.83 ms
Wall time: 2.93 ms


**Matrix Multiplication Important Rules**


1.   (3, 2) @ (2, 3) Inner dimensions must match
2.   Resultant matrix will be of outer dimernsion size (3, 3)




In [ ]:
torch.matmul(torch.rand(size=(3, 3)), torch.rand(size=(3, 4)))

tensor([[0.6289, 0.9295, 0.5944, 0.5077],
        [0.7882, 0.5771, 0.4855, 0.7639],
        [0.5556, 0.5895, 0.3593, 0.5777]])

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
tensor_A.shape, tensor_B.shape

#Inner dimensions should match,
# therefore arranging data in matrix in such a way using transpose so that matrices will multiply.

tensor_B_T = tensor_B.T

print(tensor_A.shape)
print(tensor_B.shape)
print(tensor_B_T.shape)

resultant = torch.matmul(tensor_A, tensor_B_T)
print(resultant)
print(resultant.size)




torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
<built-in method size of Tensor object at 0x7fc8fcb9a7f0>


**Tensor Aggregation (min, max, mean, Sum)**

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#torch.mean(x) . This will not work as mean requires floating point or complex dtype. arange has int64

torch.mean(x.type(torch.float32)), x.type((torch.float32)).mean()

(tensor(45.), tensor(45.))

**Positional Min and Max values in tensor**


In [ ]:
y = torch.arange(1, 100, 10)
#y.argmin()
print(torch.argmin(y))

tensor(0)


In [ ]:
y.argmax()

tensor(9)

In [ ]:
y[9]

tensor(91)

**Tensor reshape, view, squeeze, unsqueeze**

In [ ]:
x = torch.arange(1., 13.)
x.shape


torch.Size([12])

In [ ]:
x = x.reshape(4, 3)
x, x.shape

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([4, 3]))

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped[:, 0] = 5.
x_reshaped, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
y = x.view(1, 9)
y, y.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
y[:, 0] = 1.
y, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
stacked_x = torch.stack([x, x, x, x], dim = 0)
stacked_x, stacked_x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
y= x_reshaped.squeeze()
y, y.shape, x_reshaped

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

**Tensor reshape, view, squeeze, unsqueeze, stack**

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Reshaping a Tensor. Element number should not be changed.
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Checking if the altering reshaped operation changes the original x tensor or not
x_reshaped[:, 0] = 5.# taking all rows and changing 0th element
x_reshaped, x  # Yes it changes

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_view = x.view(1, 9) # same as reshaped
x_view, x_view.shape, x, x.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
x_view[:, 0] = 1.
x_view, x, x_view.shape, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([1, 9]),
 torch.Size([9]))

In [ ]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#Squeezing tensor removes 1 dimension

x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.shape, x_squeezed, x_squeezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:

x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#Unsqueezing adds 1 dimension
x_unsqueeze = x_squeezed.unsqueeze(dim = 0)
x_unsqueeze, x_unsqueeze.shape, x_squeezed, x_squeezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [ ]:
#Stacking a tensor
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
stack = torch.stack([x, x, x, x], dim = 1)
stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

**PERMUTE TENSOR REARRANGES DIMENSIONS**

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_original, x_original.shape

(tensor([[[0.2083, 0.5349, 0.9901],
          [0.5544, 0.1469, 0.1445],
          [0.0235, 0.7264, 0.0886],
          ...,
          [0.0255, 0.4193, 0.3110],
          [0.2264, 0.4755, 0.8724],
          [0.8554, 0.6715, 0.4751]],
 
         [[0.7154, 0.8907, 0.5367],
          [0.4497, 0.8122, 0.8763],
          [0.8652, 0.7010, 0.4369],
          ...,
          [0.1976, 0.5684, 0.5164],
          [0.6913, 0.2789, 0.9746],
          [0.0477, 0.9278, 0.6030]],
 
         [[0.3410, 0.2383, 0.5169],
          [0.2645, 0.1990, 0.8421],
          [0.2643, 0.4346, 0.2067],
          ...,
          [0.7539, 0.0397, 0.9281],
          [0.3852, 0.9458, 0.9595],
          [0.3994, 0.6042, 0.4872]],
 
         ...,
 
         [[0.3740, 0.8164, 0.2010],
          [0.6087, 0.9890, 0.5911],
          [0.9148, 0.6690, 0.1827],
          ...,
          [0.2852, 0.7592, 0.8280],
          [0.9978, 0.5363, 0.4393],
          [0.2394, 0.2528, 0.9001]],
 
         [[0.2072, 0.1825, 0.8349],
          [0

In [ ]:
#Permuting it
x_permute = x_original.permute(2, 0, 1)
x_permute, x_permute.shape

(tensor([[[0.2083, 0.5544, 0.0235,  ..., 0.0255, 0.2264, 0.8554],
          [0.7154, 0.4497, 0.8652,  ..., 0.1976, 0.6913, 0.0477],
          [0.3410, 0.2645, 0.2643,  ..., 0.7539, 0.3852, 0.3994],
          ...,
          [0.3740, 0.6087, 0.9148,  ..., 0.2852, 0.9978, 0.2394],
          [0.2072, 0.7692, 0.2481,  ..., 0.9850, 0.5139, 0.6141],
          [0.6676, 0.8083, 0.4897,  ..., 0.3928, 0.4867, 0.1618]],
 
         [[0.5349, 0.1469, 0.7264,  ..., 0.4193, 0.4755, 0.6715],
          [0.8907, 0.8122, 0.7010,  ..., 0.5684, 0.2789, 0.9278],
          [0.2383, 0.1990, 0.4346,  ..., 0.0397, 0.9458, 0.6042],
          ...,
          [0.8164, 0.9890, 0.6690,  ..., 0.7592, 0.5363, 0.2528],
          [0.1825, 0.2637, 0.3557,  ..., 0.9001, 0.0925, 0.5120],
          [0.6907, 0.4421, 0.5405,  ..., 0.9240, 0.2692, 0.4725]],
 
         [[0.9901, 0.1445, 0.0886,  ..., 0.3110, 0.8724, 0.4751],
          [0.5367, 0.8763, 0.4369,  ..., 0.5164, 0.9746, 0.6030],
          [0.5169, 0.8421, 0.2067,  ...,

In [ ]:
#Permute is like a view operation changes original tensor as well like following

x_permute[0, 0, 0] = 777.
x_permute

tensor([[[7.7700e+02, 5.5439e-01, 2.3548e-02,  ..., 2.5474e-02,
          2.2636e-01, 8.5540e-01],
         [7.1542e-01, 4.4972e-01, 8.6521e-01,  ..., 1.9761e-01,
          6.9133e-01, 4.7704e-02],
         [3.4102e-01, 2.6449e-01, 2.6430e-01,  ..., 7.5387e-01,
          3.8517e-01, 3.9942e-01],
         ...,
         [3.7404e-01, 6.0873e-01, 9.1483e-01,  ..., 2.8516e-01,
          9.9784e-01, 2.3945e-01],
         [2.0716e-01, 7.6919e-01, 2.4805e-01,  ..., 9.8501e-01,
          5.1394e-01, 6.1411e-01],
         [6.6760e-01, 8.0830e-01, 4.8974e-01,  ..., 3.9283e-01,
          4.8671e-01, 1.6178e-01]],

        [[5.3493e-01, 1.4688e-01, 7.2639e-01,  ..., 4.1929e-01,
          4.7554e-01, 6.7146e-01],
         [8.9074e-01, 8.1223e-01, 7.0103e-01,  ..., 5.6843e-01,
          2.7893e-01, 9.2782e-01],
         [2.3830e-01, 1.9901e-01, 4.3465e-01,  ..., 3.9711e-02,
          9.4575e-01, 6.0425e-01],
         ...,
         [8.1644e-01, 9.8897e-01, 6.6895e-01,  ..., 7.5915e-01,
          5.362

In [ ]:
x_original[0, 0, 0], x_permute[0, 0, 0]

(tensor(777.), tensor(777.))

**Indexing elements of Tensor**

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][0][1]

tensor(2)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
x[0, 1, :]

tensor([4, 5, 6])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# index on x to return 9 and 3, 6, 9

x[0][2][2]

tensor(9)

In [ ]:
x[0, :, 2]

tensor([3, 6, 9])

**NumPy arrays and PyTorch Tensors Conversions**

In [ ]:
import torch
import numpy as np
numpy_array = np.arange(1., 9.)
numpy_array, numpy_array.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8.]), dtype('float64'))

In [ ]:
tensor = torch.from_numpy(numpy_array)
tensor, numpy_array

(tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7., 8.]))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
numpy_array = numpy_array + 1
numpy_array, tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
#Tensor to array
tensor_ones = torch.ones(7)
tensor_ones.dtype

torch.float32

In [ ]:
ones_array = tensor_ones.numpy()
ones_array, tensor_ones, ones_array.dtype, tensor_ones.dtype

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]),
 dtype('float32'),
 torch.float32)

In [ ]:
tensor_ones = tensor_ones + 1
tensor_ones, ones_array

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducibility**

In [ ]:
torch.rand(3, 4)


tensor([[0.2374, 0.2053, 0.3153, 0.5810],
        [0.0098, 0.8161, 0.6360, 0.2988],
        [0.0855, 0.0884, 0.2603, 0.6141]])

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2444, 0.2621, 0.7325, 0.7517],
        [0.5437, 0.7035, 0.0753, 0.3698],
        [0.0381, 0.7021, 0.9082, 0.5862]])
tensor([[0.0788, 0.6400, 0.7175, 0.9092],
        [0.6343, 0.7691, 0.4536, 0.9397],
        [0.7640, 0.3179, 0.4713, 0.5748]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Reproducible data Seed lets us reproduce random behaviour if we suppose share notebook
import torch
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Tue Apr 30 02:52:02 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

**Running Tensor on GPU**

In [ ]:
device

'cuda'

In [ ]:
tensor = torch.tensor([1, 2, 3], device = "cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device , tensor_on_gpu

(device(type='cuda', index=0), tensor([1, 2, 3], device='cuda:0'))

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [ ]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
t1 = torch.tensor([1, 2, 3])
t1, t1.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
t2 = t1.to(device)
t2, t2.device


(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
t0 = t2.cpu().numpy()
t0

array([1, 2, 3])

In [ ]:
torch.cuda.device_count()

1